#!/bin/bash

set -e

# Script to start after the build of a fresh oardocker jessie-cigri cluster install
# from the directory containing the .oardocker directory

if [ "$1" = "" -o \! -d "$1" ]
then
  echo "You must provide the cigri sources directory!"
  echo "usage: $0 <cigri_sources_path>"
  exit 1
fi

oardocker start -v $1:/root/cigri

oardocker exec -l root server /bin/bash << EOF

  # Cigri DB installation
  cd /root/cigri/database
  ./init_db.rb -d cigri3 -u cigri3 -p cigri3 -t psql -s ./psql_structure.sql

  # Oar property "cluster" creation
  oarproperty -c -a cluster

  exit
EOF

oardocker exec -l root frontend /bin/bash << EOF

  # Cigri install
  cd /root/cigri
  make install-cigri 
  make install-autogenerated-cert

  # Apache configuration (api activation)
  ln -s /etc/cigri/api-apache.conf /etc/apache2/conf-available/cigri-api.conf
  a2enconf cigri-api

  # Cigri config file customization
  perl -pi -e 's/^DATABASE_HOST.*=.*/DATABASE_HOST = "server"/' /etc/cigri/cigri.conf

  # Cigri clusters configuration
  ./sbin/new_cluster.rb tchernobyl https://frontend/oarapi-secured/ cert oardocker oardocker '' tchernobyl oar2_5 core 100 "cluster='tchernobyl'"
  ./sbin/new_cluster.rb threemile https://frontend/oarapi-secured/ cert oardocker oardocker '' threemile oar2_5 core 10 "cluster='threemile'"
  ./sbin/new_cluster.rb fukushima https://frontend/oarapi-secured/ cert oardocker oardocker '' fukushima oar2_5 core 50 "cluster='fukushima'"

  # OAR customisation
  oarnodesetting -p cluster=threemile --sql "network_address='node1'"
  oarnodesetting -p cluster=threemile --sql "network_address='node2'"
  oarnodesetting -p cluster=threemile --sql "network_address='node3'"

  # OARAPI for CIGRI
  cp tools/oardocker/oar-restful-api-secured.conf /etc/apache2/conf-available
  a2enconf oar-restful-api-secured
  a2enmod ssl
  a2ensite default-ssl
  service apache2 reload

  exit
EOF


