#!/bin/sh
### BEGIN INIT INFO
# Provides:          cigri
# Required-Start:    networking apache2 exim4 mysql
# Required-Stop:     networking apache2 exim4 mysql
# Default-Start:     2 3 4 5
# Default-Stop:      0 6
# Short-Description: CiGri (Ciment Grid) server
### END INIT INFO

# Kill me on all errors
set -e

# Cigri environment
CIGRI_UNIX_USER="cigri"
CIGRI_CONF_FILE="/etc/cigri.conf"
[ -e /etc/cigri.conf ] || exit 0
id "$CIGRI_UNIX_USER" >/dev/null 2>&1|| exit 0
CIGRI_INSTALL_PATH=$(grep "INSTALL_PATH" $CIGRI_CONF_FILE  | sed -e 's/.*= *"\(.*\)"/\1/g')
[ "$CIGRI_INSTALL_PATH" ] || exit 0


# Start the CiGri daemons
start() {
	echo -n "Starting CiGri:"
	start-stop-daemon -d $CIGRI_INSTALL_PATH -m -p /var/run/cigri.pid -c $CIGRI_UNIX_USER -b --exec ./Almighty/AlmightyCigri.pl --start -- 2>&1 > cigri.log
        if [ "$?" -eq 0 ] ; then
	  start-stop-daemon -d $CIGRI_INSTALL_PATH/Collector -m -p /var/run/cigri_collector.pid -c $CIGRI_UNIX_USER -b --exec automatic_collect.sh --start -- 2>&1 > cigri_collector.log
          exit 0
        else
          exit 1
        fi
}

# Stop the CiGri daemons
stop() {
	echo -n "Stopping CiGri:"
        killall AlmightyCigri.pl 2>/dev/null
	killall automatic_collect.sh 2>/dev/null
        sleep 2
        killall -0 AlmightyCigri.pl 2>/dev/null
        if [ "$?" -ne 0 ] ; then
          exit 0
        else
          exit 1
        fi
}

case "$1" in
  start)
  	start ;;
  stop)
  	stop ;;
  restart|force-reload)
  	stop
	start
	;;
  *)
  	echo "Usage: $0 {start|stoprestart|force-reload}"
	exit 1
	;;
esac
